### PR TITLE
Improve TabView customizations

### PR DESCRIPTION
**Pull request by enisn**

### CODE REVIEW

**Comment by khanhzic** [comment]
error when building the source code with 2 solution, one for view, one for define. How can I fix it. Have you got any suggestion ?
Capture
Capture

**Comment by enisn** [comment]
Can you share error output?

**Comment by khanhzic** [comment]
Capture

**Comment by khanhzic** [comment]
you  can using this project to test that error
[https://github.com/khanhzic/testTabView](url)

**Comment by enisn** [comment]
> Capture

Did you add `.UseUraniumUIMaterial()` extension methods to builder in **MauiProgram.cs** ?

**Pull request merged**
