### PR TITLE
Introduce AutoCompleteTextField

### PR DESCRIPTION
**Pull request by enisn**
Closes https://github.com/enisn/UraniumUI/issues/162

### CODE REVIEW

**Comment by JhowDevBR** [comment]
work Maui?

**Comment by enisn** [comment]
This library is built on top of MAUI, it's already for MAUI

You can take look at documentation: https://enisn-projects.io/docs/en/uranium/latest/themes/material/components/AutoCompleteTextField

**Comment by JhowDevBR** [comment]
It's crashing, when I open a page it works but if I go back to root and open it again an error appears!
"System.InvalidOperationException: 'PlatformView cannot be null here"

When disabling control works...

**Comment by enisn** [comment]
> It's crashing, when I open a page it works but if I go back to root and open it again an error appears! "System.InvalidOperationException: 'PlatformView cannot be null here"
> 
> When disabling control works...

I couldn't reproduce, can you share full steps to reproduce?

**Comment by JhowDevBR** [comment]
Page01 add button:
 await Shell.Current.GoToAsync("Page02");

it will open correctly, but if you press the button to go back and click again on a button to open page02 of the crash..

**Comment by JhowDevBR** [comment]
Page02: Add control AutoCompleteTextField

**Pull request merged**
