### PR TITLE
Introduce Dropdown

### PR DESCRIPTION
**Pull request by enisn**
dropdown

uranium-dropdown-windows

uranium-dropdown-android

```xml
<uranium:Dropdown ItemsSource="{Binding Options}" SelectedItem="{Binding SelectedOption}" />
```

**TODO**

- [ ] Documentation
- [ ] Customization Options
- [ ] Implement it as **DropdownField** in Material package

### CODE REVIEW

**Comment by daltzctr** [comment]
One issue this has is that dropdown or picker on MacCatalyst shows the iOS version, which isn't really applicable. MAUI has the same issue with it's `Picker` control

**Comment by enisn** [comment]
Still couldn't figure out customization logic, so this awaits in draft. 

> One issue this has is that dropdown or picker on MacCatalyst shows the iOS version, which isn't really applicable. MAUI has the same issue with it's `Picker` control

You're right, MAUI uses UIKit for MacCatalyst output and a MAUI app behaves like iPad application that runs on MacOS. But Xamarin.Mac was using AppKit to build desktop apps for MacOS. It can be enabled in MAUI currently but it's not default. Even MAUI team uses UIKit over AppKit on desktop, I'm not sure that should I consider it for now

**Comment by DevFromDownUnder** [comment]
What is the purpose of a dropdown vs picker?

**Comment by enisn** [comment]
> What is the purpose of a dropdown vs picker?

It has a different UX. Instead of a blocking modal to pick an option, it drops down a menu to pick. On desktop it similar to picker but on mobile devices, it has a unique experience.

**Pull request merged**
