### PR TITLE
Better selection handler for Date & Time Picker

### PR DESCRIPTION
**Pull request by enisn**
Refers to https://github.com/enisn/UraniumUI/pull/804

After that PR, there was an infinity loop on windows and it was impossible to use. 

This PR applies a simplier way for the same logic and I'll implement a better datepicker with a good nullability support unlike this workaround.

### CODE REVIEW

**Comment by StepKie** [comment]
@enisn Unfortunately, this does not work in production. 

Can be checked in UraniumUI on the DatePickerField page.

It 100% worked with #804.

**Comment by enisn** [comment]
Sorry for reverting that but when Two Way Binding is used, the code was entering infinity loop, so I needed to revert. 

I'll probably go with custom implementation for DatePicker instead using built-in MAUI datepicker soon

---

BTW this PR seems solves problems with TimePicker. Only DateTimePicker has some problems

**Comment by StepKie** [comment]
> BTW this PR seems solves problems with TimePicker. Only DateTimePicker has some problems

@enisn I noticed that, but I saw that there is different implementation in your MR, so I was not surprised.

But it still doesn't work fully (for example, you can't select the default time after loading (12 AM, open picker, click ok)
it only works after first selecting something, and then clearing it. then it starts working as expected. Which will not fix the most important use case (initialize a TimePicker with null)

**Comment by StepKie** [comment]
>I'll probably go with custom implementation for DatePicker instead using built-in MAUI datepicker soon

@enisn but what is "soon"? this sounds like a non-trivial amount of work, and I had submitted my PR since this was really important to us in our production app.

**Comment by enisn** [comment]
I made some progress but android blocks me. There is no date **multiple** selection in android calendar by default. Probably I'll skip multiple selection at the first implementation

**Comment by ketakidevendra** [comment]
@enisn - Any update on this? We need this in our project.

**Pull request merged**
